ktor:
  application:
    modules:
      - ir.amirroid.simplechat.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0

db:
  username: "myuser"
  password: "mypassword"
  url: "jdbc:postgresql://localhost:5432/mydatabase"
  driver: "org.postgresql.Driver"

jwt:
  secret: "change_this_to_a_very_long_random_secret_key_!@#123"
  issuer: "http://amirroid.ir/"
  audience: "simplechat_users"
  realm: "simplechat_auth"
  expiration: 2629746000 # 1 month