ktor:
  application:
    modules:
      - ir.amirroid.simplechat.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0

db:
  username: ""
  password: ""
  url: ""
  driver: "org.postgresql.Driver"